CreateGameRoom API 구현
supershy42/game pull request #8
Opened 2024-12-02 15:06 UTC by AhnJoonSung

## 관련된 이슈 번호

- Closes #5 

## 주요 구현 사항

### Model
`GameRoom`
필드:
- `name`: 방 제목. 필수 필드
- `password`: 비밀번호, null 및 blank 가능
- `max_players`: 최대 인원. 현재는 2명 고정이라 기본 값 2로 설정해놓음. 추후에 혹시 확장될 일이 있을까 해서 추가함
함수:
- `set_password()`: 비밀번호를 해시로 저장하는 함수
- `check_password()`: 저장된 비밀번호와 전달된 비밀번호가 같은지 체크하는 함수
- `__str__()`: 출력 시 예쁘게 출려하는 함수

### Serializer:
`GameRoomSerializer`
- `id`, `name`, `password` 필드를 다룸. `password`는 `write_only`로 응답에는 포함되지 않음
- `create()`: `validated_data`를 기반으로 GameRoom 인스턴스를 생성하고 비밀번호 해싱을 돌린 뒤 DB에 `save()`

### View
`CreateGameRoomView`
- `post()`: GameRoomSerializer에 요청 데이터를 넣어서 
  - `valid` 하면 `save()`하고 `201 CREATED` 응답
  - `invalid` 하면 `400 BAD REQUEST` 응답

### Test code
- `test_create_room_without_password()`
- `test_create_room_with_password()`
- `test_create_room_with_empty_password()`
- `test_create_room_without_name()`

2024-12-07 11:17 UTC, KRimwoo approved these changes

2024-12-07 18:19 UTC, Newsujin requested changes

2024-12-07 18:19 UTC, Newsujin commented on game/serializers.py
> +class GameRoomSerializer(serializers.ModelSerializer):
`name`과 `password` 필드 길이 제한을 설정하면 좋을 것 같아요

2024-12-07 18:19 UTC, Newsujin commented on game/tests.py
> +    def test_create_room_with_empty_password(self):
비밀번호 길이 제한을 설정하면 empty password 테스트는 없애야 할 것 같습니다!

2024-12-08 07:07 UTC, AhnJoonSung commented on game/models.py
> +    def check_password(self, raw_password):
요거는 모델에 있는게 맞다 생각합니다. 
두 함수가 모델의 필드를 직접 다루는 함수이고, 외부에서 모델 없이 저 기능만 따로 쓸 일이 없어서 
모델에서 관리하는게 객체지향적으로 더 역할분리가 잘 된거라 봅니다

2024-12-08 07:08 UTC, AhnJoonSung commented on game/serializers.py
> +class GameRoomSerializer(serializers.ModelSerializer):
오까이 대충 20글자로 할게유

2024-12-08 07:12 UTC, AhnJoonSung commented on game/tests.py
> +    def test_create_room_with_empty_password(self):
오케이 최소 길이도 해두겠습니다

2024-12-08 09:40 UTC, Newsujin approved these changes
수고하셨슴다!!!!!!!

2024-12-08 10:03 UTC, Newsujin commented on game/models.py
> -    password = models.CharField(max_length=255, null=True, blank=True)
password 빈문자열 에러 처리 하려면 blank=True 옵션 빼야 할 거 같아요!

2024-12-08 10:04 UTC, Newsujin commented on game/serializers.py
> -        allow_blank=True,
여기도 기본 옵션이 allow_blank=True라 False 추가해주면 될 것 같슴니다

2024-12-08 12:41 UTC, AhnJoonSung commented on game/serializers.py
> -        allow_blank=True,
기본 옵션 False 아닌가요? 요건 테스트 코드로 확인했습니다. 
근데 프론트에서 비밀번호 없을 때 빈문자열로 할 것 같다 하셔서 다음 피알에서 True로 해야할듯요

2024-12-09 05:57 UTC, KRimwoo approved these changes

2024-12-09 14:34 UTC, bean-baek approved these changes

2024-12-09 14:40 UTC, merged